[package]
name = "zickzack"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "zickzack"
path = "src/bin.rs"

[dependencies]
derive_more = "0.99"
actix-web = "4"
actix-rt = "2"
serde = "1.0"
serde_derive = "1.0"
actix-files = "0.6.2"
rand = "0.8.5"
env_logger = "0.10.0"
